-- Magnitude Analysis Formula is ∑[Measure] By [Dimension]
--example: Total Sales By Country / Total Quantity By Category / Average Price By Product / Total Orders By Customer

-- Find total customers by countries
SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

--Find total customers by gender
SELECT
gender,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT category,
COUNT(product_key) AS total_products FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

--What is the average costs in each category?
SELECT category,
AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;
SELECT * FROM gold.fact_sales;

--what is the total revenue generated for each category?
-- TOTAL REVENUE IS FROM FACT_SALES AND CATEGORY IS FROM DIM_PRODUCTS, SO JOIN TABLES FIRST
SELECT 
p.category, SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

--Find total revenue generated by each customer
SELECT * FROM gold.fact_sales 
SELECT * FROM gold.dim_customers

SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
